package Enum;

public enum ProtocolErrors {
    User_DOES_NOTEXIST,
    UNEXPECTED_RETURN_CMD,
    UNRECOGNIZABLE_CMD,
    CHESSENGINE_NOT_FOUND,
    CHESSENGINE_NOT_STARTED,
    CHESSENGINE_NOT_RUNNING,
    CHESSENGINE_OPTION_DOES_NOTEXIST,
    CHESSENGINE_PAWN_COLLIDED_STRAIGHT,
    CHESSENGINE_PAWN_COLLIDED_DIAGONAL_OREMPTYCELLTHERE,
    CHESSENGINE_STARTING_CELL_EMPTY,
    CHESSENGINE_NOT_THAT_COLORS_TURN,
    CHESSENGINE_MOVE_INVALID_OR_BLOCKED_BY_OWN_COLOR,
    CHESSENGINE_CANNOT_CASTLE_KING_SIDE,
    CHESSENGINE_CANNOT_CASTLE_QUEEN_SIDE,
    CHESSENGINE_MOVE_FORMAT_INVALID

}
